[workflow]
workflow_schedule_interval = "@daily"
sequential_queue = "sequential"
default_queue = "general"

[db]
db_identifier = "brennan-database"
db_connection = "brennan-rds-postgres-test"
username = 'postgres'
password = 'brennanDB123'
host = 'brennan-database.cvwhaidrmrqj.us-east-2.rds.amazonaws.com'
port = '5432'  # Default port for PostgreSQL
default_db = 'postgres'  # Default database you can connect to
db_name = 'lab8db'
db_alchemy_driver = "postgresql+psycopg2"

[files]
s3_bucket = "de300spring2024-brennanb-airflow"
s3_file_key = "wine.csv"
remote_file = "wine.csv"
local_file = "wine.csv"

[ml]
train_test_ratio = 0.2
outliers_std_factor = 3
labels = "Wine"
tolerance = 0.01
perturbation_std = 1.2
max_perturbation_iterations = 50
confidence_level = 0.95
