# Use a Python base image
FROM python:3.11-bullseye



# Create a new user and set permissions
RUN useradd -m brennan


# Set ownership of the working directory
WORKDIR /app
RUN chown -R brennan /app



# Set working directory
WORKDIR /app

# Install MySQL client library
# RUN apt-get update && apt-get install -y mysql-client


# Create a virtual environment
RUN python -m venv /venv

# Activate the virtual environment
ENV PATH="/venv/bin:${PATH}"


# Install Python dependencies
RUN pip install mysql-connector-python pandas jupyter sqlalchemy matplotlib seaborn scipy statsmodels





#switch to non-root user
USER brennan


# Copy the script and CSV file into the container
COPY src/EDA.ipynb .
COPY data/heart_disease.csv .


# Expose the Jupyter port
EXPOSE 8888

# Start Jupyter Notebook when the container starts
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
# CMD ["/bin/bash"]